### PR TITLE
fix nullable type

### LINKED ISSUE #80: Bug nullable type
This kind of error is generated in `src/graphql/generated/types.ts` in the latest change of nullable types.

`
Property 'description' is incompatible with index signature.
    Type 'Type<Kind.scalar, string, any> | null | undefined' is not assignable to type 'ValidType[] | Type<any, any, any> | FieldsTypeArg<any, any> | null'.
      Type 'undefined' is not assignable to type 'ValidType[] | Type<any, any, any> | FieldsTypeArg<any, any> | null'.
`

I will send a PR that fixes it

### PR DESCRIPTION
**Pull request by PabloSzx**
fixes #80

### CODE REVIEW

**Comment by Yomanz** [comment]
> 
> 
> fixes #80

your scuffed mate this fixes nothing

**Comment by PabloSzx** [comment]
@Yomanz there was a missing type fix here https://github.com/samdenty/gqless/blob/master/gqless/src/Type.ts#L42

**Comment by PabloSzx** [comment]
I made another PR #83

**Comment by Yomanz** [comment]
> 
> 
> I made another PR #83

Yeah, I just noticed that and committed it :)

**Comment by Arrow7000** [comment]
Hey guys, love the project!

Is this PR supposed to fix this error?
```
Type 'undefined' is not assignable to type 'Type<any, any, any> | ValidType[] | FieldsTypeArg<any, any> | null'
```
Because that's the error I'm getting and I've just installed gqless. If it's still happening for me because the fix hasn't been released yet do you know when it will be released? 🙏 

Great work!

**Comment by PabloSzx** [comment]
@Arrow7000 yes, it's that error, the fix is made, it just hasn't been released

**Comment by Arrow7000** [comment]
Thank you, I patched it manually and the errors disappeared 😄

**Comment by PabloSzx** [comment]
@Arrow7000 A new gqless version was released, the fix should be included 👌

**Pull request merged**
